### PR TITLE
Way to access JWT payload

### PR DESCRIPTION
**Pull request by RiteshParyali**
An instruction to access JWT payload .

A me

### CODE REVIEW

**Comment by markstory** [comment]
Were you not able to use the `returnPayload` [option of the JwtAuthenticator](https://book.cakephp.org/authentication/2/en/authenticators.html#jwt)? 

Parsing a JWT token in application code is something I would prefer we didn't include in the docs as we should have abstractions so that configuration data doesn't need to be duplicated.

**Comment by RiteshParyali** [comment]
Thank you. 
But still have an issue..

when returnPayload is false **$this->Authentication->getIdentity()** , is returning the data/row for the users from table.
and when returnPayload is true , then **$this->Authentication->getIdentity()** is returning only the _payload_,

Is is possible to get both ?

**Comment by markstory** [comment]
> Is is possible to get both ?

No. You can write your own authentication adapter if you need that.

**Comment by RiteshParyali** [comment]
> > Is is possible to get both ?
> 
> No. You can write your own authentication adapter if you need that.

Then this instruction can be useful

**Comment by markstory** [comment]
> Then this instruction can be useful

Sure, but including documentation for every potential task a user might want to do with their application code would make the documentation hard to navigate and use.

**Comment by ADmad** [comment]
In general instructions for how to extend and modify a class to suit ones specific needs is not something we can include in the docs.

You can use one of our support forums for help.

**Pull request closed without merging**
