### PR TITLE
Fix up get() method and docs.

### PR DESCRIPTION
**Pull request by dereuromark**
Resolves https://github.com/cakephp/authentication/issues/249

get() can be made typehinted dynamically via IDE extension, the others cannot.
See [meta](https://github.com/dereuromark/cakephp-ide-helper/blob/master/tests/test_files/meta/phpstorm/.meta.php) file.

### CODE REVIEW

**Comment by dereuromark** [comment]
We can backport it, but technically it is a fatal error if someone extended that method and visibilitiy changes.

**Comment by markstory** [comment]
True. But part of our BC guide lines allow us to promote a protected method to public in a minor release.

**Comment by dereuromark** [comment]
Lets wait till 1.x is merged into 2.x then we see what is still left of this.

**Comment by dereuromark** [comment]
So whats the status on this?

**Comment by ADmad** [comment]
Skimming through the diff I think most of the changes are already done. It would be best to rebase this branch on top of 2.x to get a clear picture.

**Comment by dereuromark** [comment]
Looks like it can indeed be closed now

**Pull request closed without merging**
