### PR TITLE
Make error messages more consistent.

### PR DESCRIPTION
**Pull request by markstory**
* Use plural forms where they should be used.
* Use backticks instead of " for classnames.

### CODE REVIEW

**Comment by burzum** [comment]
Looks good.

**Comment by burzum** [comment]
@markstory this codecov is anoying... Why is it red here!?

**Comment by markstory** [comment]
@burzum no idea, I think it didn't like that coverage didn't improve.

**Comment by burzum** [comment]
@markstory It's pretty annoying because it always looks like it failed and you need to check the CI checks. :(

**Pull request merged**
