### PR TITLE
#2 Namespace rename

### PR DESCRIPTION
**Pull request by burzum**

### CODE REVIEW

**Comment by dereuromark** [comment]
:+1:

**Comment by burzum** [comment]
No idea why GH has a merge conflict, worked fine locally without getting a conflict. Merged i manually and pushed to master.

**Comment by dereuromark** [comment]
Shouldnt the whole plugin then be renamed from

    cakephp/middleware-authentication

to 

    cakephp/authentication

?

I mean Middleware is a specific pattern and implementation detail that does not need to be reflected in the name. How it is done internally should not matter to "what it does" which should be reflected in the name.

**Comment by burzum** [comment]
Yes, I agree

**Pull request closed without merging**
