### PR TITLE
Legacy passwordhasher

### PR DESCRIPTION
**Pull request by burzum**

### CODE REVIEW

**Comment by robertpustulka** [comment]
cakephp/event could also be moved to suggest as only a component uses events.

**Comment by robertpustulka** [comment]
Tests probably should be updated not to use any of the ldap-ext features then.

**Comment by burzum** [comment]
> Tests probably should be updated not to use any of the ldap-ext features then. 

@robertpustulka do you want to do it or @cleptric?

**Comment by robertpustulka** [comment]
I could do it next week.

**Comment by burzum** [comment]
Merging this. Codecov tells me -0.16 but [here](https://codecov.io/gh/cakephp/authentication/compare/0cab081b568050ca02548642b649990e36196022...bcd1674c2ad179e0969196fb21e471ae1a717c38/changes) it tells me: No changed detected that need to be reviewed. 😟

**Pull request merged**
