### PR TITLE
Move Authentication service checks for early failures.

### PR DESCRIPTION
**Pull request by robertpustulka**
`null` and `instanceof` checks should be executed early.

### CODE REVIEW

**Comment by jeremyharris** [comment]
This is basically a revert of https://github.com/cakephp/authentication/pull/201 which may cause bake to start failing again.

**Comment by robertpustulka** [comment]
@jeremyharris sorry, I wasn't aware of that.

Maybe the check should be moved to the `beforeFilter` callback? `beforeFilter` expectes that the `$this->_authentication` is valid, but this is checked later in `startup`.

**Comment by jeremyharris** [comment]
@robertpustulka no worries! Just wanted to make you aware. I think `beforeFilter` will work just fine :)

**Comment by markstory** [comment]
Good catch @jeremyharris . `beforeFilter()` would be a good place for these.

**Pull request merged**
