### PR TITLE
Add default config 'identify' to SessionAuthenticator

### PR DESCRIPTION
**Pull request by littleylv**
#97

### CODE REVIEW

**Comment by dereuromark** [comment]
Wouldnt this go into https://github.com/cakephp/authentication/blob/master/src/Authenticator/AbstractAuthenticator.php#L32-L35 ?

**Comment by dereuromark** [comment]
Or a _defaultConfig attribute at least inside the SessionAuthenticator class?

**Comment by littleylv** [comment]
I didn't see any other authenticator use this key except session

**Comment by dereuromark** [comment]
I see, merging will not work otherwise with the property.

**Pull request merged**
