### PR TITLE
Make sure object alternative return value is null instead of bool.

### PR DESCRIPTION
**Pull request by dereuromark**
Closes https://github.com/cakephp/authentication/issues/49

We should run phpstan over it to make sure.

Awesome work so far, guys!

### CODE REVIEW

**Comment by markstory** [comment]
There is [one failing test](https://travis-ci.org/cakephp/authentication/jobs/197052761)

**Comment by dereuromark** [comment]
Thx, I also made sure travis doesnt use the global phpunit as that one is buggy.

**Comment by dereuromark** [comment]
Darn I accidently pushed that to master, I reverted the test.
Strange, it didnt fail for me running locally, though.

**Comment by dereuromark** [comment]
OK, I think I figured it out.

**Comment by burzum** [comment]
:+I think it's OK.

**Pull request merged**
